Task 1 — Create a Tensor
Create a 1D tensor containing the following sensor readings:
25.2, 25.5, 24.9, 26.1, 25.8
Perform the following:
Print the tensor. 
Print its shape. 
Print the number of dimensions. 
Print the number of elements. 
The goal is to make to all remember the  difference between tensor values, shape, size, and number of dimensions.

In [1]:
import tensorflow as tf 
ten = tf.constant([25.2, 25.5, 24.9, 26.1, 25.8])

In [13]:
print(ten)

tf.Tensor([25.2 25.5 24.9 26.1 25.8], shape=(5,), dtype=float32)


In [11]:
print("Number of dimensions:", ten.ndim)
print("Shape of the tensor:", ten.shape)
print("Number of elements in the tensor:", tf.size(ten).numpy())

Number of dimensions: 1
Shape of the tensor: (5,)
Number of elements in the tensor: 5


Task 2 — From Vector to Matrix
Suppose an industrial system has 4 sensors recording measurements for 5 time steps.
Create the following data:
Temperature:  [25, 26, 25, 27, 28]
Pressure:     [101, 102, 101, 103, 104]
Humidity:     [60, 62, 61, 63, 64]
Vibration:    [0.2, 0.3, 0.2, 0.4, 0.5]
Create a tensor with shape:
(5, 4)
where:
rows    → time
columns → sensors

Then print:
shape 
number of dimensions 
first time step 
temperature readings 
vibration readings 
Think: What does each axis represent?

In [18]:
temperature =   [25, 26, 25, 27, 28]
pressure =      [101, 102, 101, 103, 104]
humidity =    [60, 62, 61, 63, 64]
vibration =    [0.2, 0.3, 0.2, 0.4, 0.5]

# Convert individual lists to float32 tensors first
t_tensor = tf.convert_to_tensor(temperature, dtype=tf.float32)
p_tensor = tf.convert_to_tensor(pressure, dtype=tf.float32)
h_tensor = tf.convert_to_tensor(humidity, dtype=tf.float32)
v_tensor = tf.convert_to_tensor(vibration, dtype=tf.float32)

# Now stack them together seamlessly!
sensor_tensor = tf.stack([t_tensor, p_tensor, h_tensor, v_tensor], axis=1)


print(sensor_tensor.shape)
print("number of dimension", sensor_tensor.ndim)

first_time_step = sensor_tensor[0, :]
print("first time step ", first_time_step)


(5, 4)
number of dimension 2
first time step  tf.Tensor([ 25.  101.   60.    0.2], shape=(4,), dtype=float32)


In [20]:
Temperature_reading = sensor_tensor[:,0]
print(Temperature_reading)

tf.Tensor([25. 26. 25. 27. 28.], shape=(5,), dtype=float32)


In [21]:
vibration_reading = sensor_tensor[:,3]

print("Vibration Reading :  ", vibration_reading)

Vibration Reading :   tf.Tensor([0.2 0.3 0.2 0.4 0.5], shape=(5,), dtype=float32)


In [22]:
print("Axis 0 represent  Time Steps rows of tensor")
print("Axis 1 represent  Feature of columns of tensor ")

Axis 0 represent  Time Steps rows of tensor
Axis 1 represent  Feature of columns of tensor 


Task 3 — Create a 3D Tensor
Now suppose we monitor 10 machines.
Each machine has:
5 time steps 
4 sensors 
Create a tensor with shape:
(10, 5, 4)
Interpret the dimensions as:
Machine × Time × Sensor
Then answer using Python:
What is the temperature reading of machine 3 at time step 2? 
Extract all sensor readings of machine 5. 
Extract all machines at time step 1. 
Extract the readings of sensor 4 from all machines and all time steps. 

In [23]:
import tensorflow as tf
import numpy as np


single_machine_data = np.array([
    [25.0, 101.0, 60.0, 0.2],  
    [26.0, 102.0, 62.0, 0.3], 
    [25.0, 101.0, 61.0, 0.2],  
    [27.0, 103.0, 63.0, 0.4],  
    [28.0, 104.0, 64.0, 0.5]   
])

#
machines_data = np.array([single_machine_data for _ in range(10)])

# Convert to a TensorFlow 3D Tensor
system_tensor = tf.constant(machines_data, dtype=tf.float32)

print(f"Successfully created a 3D Tensor with shape: {system_tensor.shape}")


Successfully created a 3D Tensor with shape: (10, 5, 4)


In [25]:
# hat is the temperature reading of machine 3 at time step 2? 

temp_m3_t2 = system_tensor[2, 1, 0]
print("Temperature (M3, T2):", temp_m3_t2.numpy()) # Output: 26.0


Temperature (M3, T2): 26.0


In [26]:
#Extract all sensor readings of machine 5. 

machine5 = system_tensor[4,:,:]
print(machine5)

tf.Tensor(
[[ 25.  101.   60.    0.2]
 [ 26.  102.   62.    0.3]
 [ 25.  101.   61.    0.2]
 [ 27.  103.   63.    0.4]
 [ 28.  104.   64.    0.5]], shape=(5, 4), dtype=float32)


In [27]:
#Extract all machines at time step 1. 
time1 = system_tensor[:,0,:]
print("Time Step 1 Matrix Shape:", time1.shape)

Time Step 1 Matrix Shape: (10, 4)


In [28]:
#Extract the readings of sensor 4 from all machines and all time steps.

sensor4 = system_tensor[:,:,3]
print(sensor4)

tf.Tensor(
[[0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]
 [0.2 0.3 0.2 0.4 0.5]], shape=(10, 5), dtype=float32)


Task 4 — Indexing a Tensor
Create:
X = np.arange(24).reshape(2, 3, 4)
Print X.
Now investigate:
X[0]
X[1]
X[0, 0]
X[0, 0, 0]

Answer:
What is the shape of X? 
What does X[0] represent? 
What does X[0,0] represent? 
What does X[0,0,0] represent? 


In [29]:
X = np.arange(24).reshape(2, 3, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
#What is the shape of X? 
print(X.shape)

(2, 3, 4)


In [31]:
#What does X[0] represent? 
print(X[0])

print("It represent first dimension of three dimension")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
It represent first dimension of three dimension


In [33]:
#What does X[0,0] represent? 

print(X[0,0])

print("It represent second dimention first row")

[0 1 2 3]
It represent second dimention first row


In [34]:
#What does X[0,0,0] represent? 

print(X[0,0,0])

print("It represent third dimenson by selecting particularly value in third dimension")

0
It represent third dimenson by selecting particularly value in third dimension


Task 5 — Slicing
Using:
X = np.arange(60).reshape(3, 4, 5)
Perform:
Extract the first block: X[0]
Extract the first row from every block.
Extract the third element from every row and every block.
Extract the last two elements along the final dimension. Then print the resulting shapes.

In [36]:
X = np.arange(60).reshape(3, 4, 5)

#Extract the first block: X[0]
first_block = X[0]
print(first_block)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [37]:
#Extract the first row from every block.

all_first_row = X[:,0,:]
print(all_first_row)

[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [40 41 42 43 44]]


In [38]:
#Extract the third element from every row and every block.

extract = X[:,:,2]

print(extract)

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]


In [41]:
#Extract the last two elements along the final dimension. Then print the resulting shapes.

last_two_elements = X[:, :, -2:]

print(last_two_elements.shape)

(3, 4, 2)


 
Task 6 — Image Tensor
Create a synthetic RGB image tensor:
Height = 128
Width = 128
Channels = 3
Create:
image = ...
with shape: (128, 128, 3)
Then:
Print the shape. 
Extract the red channel. 
Extract the green channel. 
Extract the blue channel. 
Find the maximum pixel value. 
Find the minimum pixel value. 

In [42]:
image = tf.random.uniform(shape=(128, 128, 3), minval=0, maxval=256, dtype=tf.int32)
print("Image Shape:", image.shape)

Image Shape: (128, 128, 3)


In [43]:
#Extract the red channel. 
red_channel   = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel  = image[:, :, 2]

max_val = tf.reduce_max(image)
min_val = tf.reduce_min(image)

print("Red Channel Shape:", red_channel.shape)
print("Green Channel Shape:", green_channel.shape)
print("Blue Channel Shape:", blue_channel.shape)
print("Maximum Pixel Value:", max_val.numpy())
print("Minimum Pixel Value:", min_val.numpy())

Red Channel Shape: (128, 128)
Green Channel Shape: (128, 128)
Blue Channel Shape: (128, 128)
Maximum Pixel Value: 255
Minimum Pixel Value: 0


Task 7 — Batch of Images
Now suppose you have 32 RGB images, each of size 128 × 128.
Create a tensor with shape:
(32, 128, 128, 3)
using random values.
Then:
Extract the first image. 
Extract the first 10 images. 
Extract the red channel from all images. 
Extract pixel (50, 50) from every image. 
Print the shape after each operation. 

In [47]:
batch_images = tf.random.uniform(shape=(32, 128, 128, 3), minval=0, maxval=256, dtype=tf.int32)
first_image = batch_images[0, :, :, :]
print("1. First Image Shape:              ", first_image.shape)



1. First Image Shape:               (128, 128, 3)


In [48]:
first_10_images = batch_images[0:10, :, :, :]
print("2. First 10 Images Shape:          ", first_10_images.shape)

2. First 10 Images Shape:           (10, 128, 128, 3)


In [49]:
all_red_channels = batch_images[:, :, :, 0]
print("3. All Red Channels Shape:         ", all_red_channels.shape)

3. All Red Channels Shape:          (32, 128, 128)


In [50]:
pixel_50_50_all = batch_images[:, 50, 50, :]
print("4. Pixel (50,50) Every Image Shape:", pixel_50_50_all.shape)

4. Pixel (50,50) Every Image Shape: (32, 3)


Task 8 — Reshape
Create:
X = np.arange(24)
Reshape it into:
(4, 6)
(2, 3, 4)
(6, 4)
(24,)
For each one:
Print the tensor. 
Print its shape. 
Print its number of dimensions. 


In [52]:
X = np.arange(24)
reshape1 = X.reshape(4,6)
print(reshape1)
print("Shape : ",reshape1.shape)
print("Dimension :  ",reshape1.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Shape :  (4, 6)
Dimension :   2


In [53]:
reshape1 = X.reshape(2,3,4)
print(reshape1)
print("Shape : ",reshape1.shape)
print("Dimension :  ",reshape1.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape :  (2, 3, 4)
Dimension :   3


In [54]:
reshape1 = X.reshape(6,4)
print(reshape1)
print("Shape : ",reshape1.shape)
print("Dimension :  ",reshape1.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Shape :  (6, 4)
Dimension :   2


In [55]:
reshape1 = X.reshape(24,)
print(reshape1)
print("Shape : ",reshape1.shape)
print("Dimension :  ",reshape1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape :  (24,)
Dimension :   1


Task 9 — Reshape vs Transpose
Create:
X = np.arange(24).reshape(2, 3, 4)
Now perform:
X.reshape(3, 2, 4) and X.transpose(1, 0, 2)
Compare the results.
Are these two operations doing the same thing?

In [59]:
X = np.arange(24).reshape(2, 3, 4)
print(X.reshape(3, 2, 4))
print("Shape : ",X.reshape(3, 2, 4).shape)
print("Transposed :  ")
print(X.transpose(1, 0, 2))
print("Shape. : ",X.transpose(1, 0, 2).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
Shape :  (3, 2, 4)
Transposed :  
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
Shape. :  (3, 2, 4)


In [60]:
print("From the result data patterns looks different and  shape & dimension is same")

From the result data patterns looks different and  shape & dimension is same


Task 10 — Broadcasting
Create:
X = np.ones((3, 4))
and:
b = np.array([10, 20, 30, 40])
Calculate: X + b
Then try: X * b
Question: Why can a (4,) tensor be combined with a (3,4) tensor?

In [ ]:
X = np.ones((3, 4))
b = np.array([10, 20, 30, 40])

addition = X + b
Multiply = X * b


1Dimension Alignment: NumPy aligns the shapes starting from the right side (trailing dimensions):X Shape: (3, 4) 
b Shape: (   4)
The Compatibility Check: Two axes are compatible if they are equal, or if one of them is 1. In this case, the trailing dimensions match perfectly (4 and 4).

Virtual Stretching: Because b lacks a first dimension, NumPy virtually adds a dimension of size 1 to its front, treating it as (1, 4). It then replicates (or "broadcasts") that single row down 3 times until it perfectly matches the (3, 4) footprint of X.

Task 11 — Broadcasting with Sensor Data
Suppose:
X.shape = (100, 10)
represents:
100 samples × 10 sensors
The calibration offset for each sensor is:
[1.2, 0.8, 1.1, 0.5, 0.9, 1.0, 0.7, 1.3, 0.6, 0.4]
Create the tensor and subtract the calibration offsets.
Your output should remain:
(100, 10)
Goal: See broadcasting in an actual engineering problem.

In [62]:
import numpy as np


X = np.random.uniform(low=10.0, high=50.0, size=(100, 10))


offset = np.array([1.2, 0.8, 1.1, 0.5, 0.9, 1.0, 0.7, 1.3, 0.6, 0.4])

calibrated_X = X - offset

print("Original Sensor Data Shape: ", X.shape)
print("Calibration Offset Shape:   ", offset.shape)
print("Calibrated Data Shape:       ", calibrated_X.shape)


print("\n--- Verification on Sensor 0 (First 3 samples) ---")
print("Original:  ", X[:3, 0])
print("Calibrated:", calibrated_X[:3, 0])



Original Sensor Data Shape:  (100, 10)
Calibration Offset Shape:    (10,)
Calibrated Data Shape:        (100, 10)

--- Verification on Sensor 0 (First 3 samples) ---
Original:   [46.54024624 18.12296045 18.42505477]
Calibrated: [45.34024624 16.92296045 17.22505477]


This works flawlessly because of your trailing dimension alignment rule:
X Shape: (100, 10)
offset Shape: (     10)
Because the rightmost dimensions match (10 and 10), NumPy virtually duplicates the 10-element offset array 100 times downwards.This means Sensor 0's value (1.2) is subtracted from all 100 entries in Column 0, Sensor 1's value (0.8) is subtracted from all 100 entries in Column 1, and so on. You correct 1,000 data points in a single line of code without a single slow for loop.

Task 12 — Tensor Aggregation
Create:
X = np.random.randn(100, 20, 5)
Interpret it as:
100 machines
20 time steps
5 sensors
Calculate:
Mean across time. 
Mean across sensors. 
Mean across machines. 
Maximum sensor value across time. 
Standard deviation across time. 
Predict the resulting shape before running the code.

In [63]:
X = np.random.randn(100, 20, 5)


mean_time = X.mean(axis=1)

mean_sensors = X.mean(axis=2)

mean_machines = X.mean(axis=0)

max_time = X.max(axis=1)

std_time = X.std(axis=1)

# Print and verify the results match our predictions
print(f"Original Tensor Shape:             {X.shape}")
print(f"Mean across time shape (axis=1):   {mean_time.shape}")
print(f"Mean across sensors shape (axis=2):{mean_sensors.shape}")
print(f"Mean across machines shape (axis=0):{mean_machines.shape}")
print(f"Max across time shape (axis=1):    {max_time.shape}")
print(f"Std dev across time shape (axis=1): {std_time.shape}")

Original Tensor Shape:             (100, 20, 5)
Mean across time shape (axis=1):   (100, 5)
Mean across sensors shape (axis=2):(100, 20)
Mean across machines shape (axis=0):(20, 5)
Max across time shape (axis=1):    (100, 5)
Std dev across time shape (axis=1): (100, 5)


Task 13 — Normalize a Tensor
Create sensor data:
X = np.random.randn(100, 20, 5)
Calculate the mean and standard deviation for each sensor.
Normalize the tensor using:
 
Then verify:
mean ≈ 0
standard deviation ≈ 1

In [ ]:
mean = X.mean(axis=(0, 1), keepdims=True)
std = X.std(axis=(0, 1), keepdims=True)

X_normalized = (X - mean) / std


post_mean = X_normalized.mean(axis=(0, 1))
post_std = X_normalized.std(axis=(0, 1))


print(f"Original shape:            {X.shape}")
print(f"Calculated mean shape:     {mean.shape} (due to keepdims=True)")
print(f"Normalized shape:          {X_normalized.shape}\n")

print("--- Verification per Sensor (Should be Mean ≈ 0, Std ≈ 1) ---")
for i in range(5):
    print(f"Sensor {i} -> Mean: {post_mean[i]:.6f} | Std Dev: {post_std[i]:.6f}")

Original shape:            (100, 20, 5)
Calculated mean shape:     (1, 1, 5) (due to keepdims=True)
Normalized shape:          (100, 20, 5)

--- Verification per Sensor (Should be Mean ≈ 0, Std ≈ 1) ---
Sensor 0 -> Mean: -0.000000 | Std Dev: 1.000000
Sensor 1 -> Mean: 0.000000 | Std Dev: 1.000000
Sensor 2 -> Mean: 0.000000 | Std Dev: 1.000000
Sensor 3 -> Mean: 0.000000 | Std Dev: 1.000000
Sensor 4 -> Mean: 0.000000 | Std Dev: 1.000000


Task 14 — Flattening
Create an image:
(28, 28, 3)
Flatten it into:
(2352,)
Then create a batch of 64 images:
(64, 28, 28, 3)
Flatten each image while keeping the batch dimension.
Expected shape: 	(64, 2352)
Why shouldn't we simply flatten the entire tensor into (150528,) when working with a batch?

In [65]:

image = np.random.randn(28, 28, 3)


flat_image = image.flatten()

batch_images = np.random.randn(64, 28, 28, 3)

flat_batch = batch_images.reshape(64, -1)

print(f"Single image shape:            {image.shape}")
print(f"Flattened single image shape:  {flat_image.shape}")
print(f"Batch images shape:            {batch_images.shape}")
print(f"Flattened batch shape:         {flat_batch.shape}")


Single image shape:            (28, 28, 3)
Flattened single image shape:  (2352,)
Batch images shape:            (64, 28, 28, 3)
Flattened batch shape:         (64, 2352)


Task 15 — Concatenation
Suppose a model produces two feature tensors:
Visual features:
(32, 128)

Sensor features:
(32, 64)
Combine them into a single feature tensor.
Expected result:
(32, 192)
Use tensor concatenation.
Then explain:
Why can we concatenate along the feature dimension but not arbitrarily along every dimension?

In [66]:
import numpy as np

visual_features = np.random.randn(32, 128)
sensor_features = np.random.randn(32, 64)


combined_features = np.concatenate((visual_features, sensor_features), axis=1)


print(f"Visual features shape: {visual_features.shape}")
print(f"Sensor features shape: {sensor_features.shape}")
print(f"Combined shape:        {combined_features.shape}")  


Visual features shape: (32, 128)
Sensor features shape: (32, 64)
Combined shape:        (32, 192)


1. The "All Other Dimensions Must Match" Rule: When you concatenate along axis=1 (the features), NumPy stitches the arrays side-by-side. This works because both tensors agree on axis=0 (they both have exactly 32 samples). Every single sample row matches up perfectly.
2. Why axis=0 Fails Here: If you attempted to concatenate them along axis=0 (stacking them vertically), NumPy would try to place a 64-column matrix directly beneath a 128-column matrix. This creates a structural mismatch—tensors must be uniform blocks (matrices cannot have jagged rows of varying widths).

Task 16 — Practical Mini Challenge: Sensor Dataset
Create a synthetic dataset representing:
500 machines
60 time steps
8 sensors

Therefore:

X.shape = (500, 60, 8)

Perform the following:
Extract machine 10. 
Extract the first 20 time steps. 
Extract sensor 5 from all machines. 
Calculate the average value of every sensor. 
Calculate the average value at every time step. 
Find the machine with the highest average sensor reading. 
Normalize each sensor. 
Split the tensor into: 
Training: 400 machines 
Testing: 100 machines 


In [67]:
import numpy as np

np.random.seed(42)

X = np.random.randn(500, 60, 8)

machine_10 = X[10, :, :]
first_20_steps = X[:, :20, :]
sensor_5_all = X[:, :, 5]

avg_per_sensor = X.mean(axis=(0, 1))
avg_per_timestep = X.mean(axis=(0, 2))

machine_means = X.mean(axis=(1, 2))
highest_avg_machine_idx = np.argmax(machine_means)

sensor_means = X.mean(axis=(0, 1), keepdims=True)
sensor_stds = X.std(axis=(0, 1), keepdims=True)
X_normalized = (X - sensor_means) / sensor_stds

X_train = X_normalized[:400, :, :]
X_test = X_normalized[400:, :, :]

print(f"0. Initial dataset shape:                     {X.shape}")
print(f"1. Machine 10 shape:                          {machine_10.shape}")
print(f"2. First 20 time steps shape:                 {first_20_steps.shape}")
print(f"3. Sensor 5 across all machines shape:        {sensor_5_all.shape}")
print(f"4. Average per sensor shape:                  {avg_per_sensor.shape}")
print(f"5. Average per time step shape:               {avg_per_timestep.shape}")
print(f"6. Machine ID with highest average reading:   #{highest_avg_machine_idx}")
print(f"7. Normalized dataset shape:                  {X_normalized.shape}")
print(f"8. Train split shape | Test split shape:      {X_train.shape} | {X_test.shape}")


0. Initial dataset shape:                     (500, 60, 8)
1. Machine 10 shape:                          (60, 8)
2. First 20 time steps shape:                 (500, 20, 8)
3. Sensor 5 across all machines shape:        (500, 60)
4. Average per sensor shape:                  (8,)
5. Average per time step shape:               (60,)
6. Machine ID with highest average reading:   #338
7. Normalized dataset shape:                  (500, 60, 8)
8. Train split shape | Test split shape:      (400, 60, 8) | (100, 60, 8)
