# 3D Array

In [22]:
import numpy as np

arr = np.array([
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ],

    [
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]
    ],

    [ 
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]
    ]
])

print(arr.shape)

(3, 4, 5)


In [11]:
print(arr[0,0,0])
print(arr[0,2,4])
print(arr[1,1,2])
print(arr[1,2,3])
print(arr[2,0,4])
print(arr[2,3,1])
print(arr[2,1,3])
print(arr[1,3,4])

10
24
37
43
54
66
58
49


In [12]:
# Assignment: 3D Array Indexing & Slicing

# Section A – Access Individual Elements

# Write a statement to extract:

print(arr[0,0,0])
print(arr[0,2,4])
print(arr[1,1,2])
print(arr[1,2,3])
print(arr[2,0,4])
print(arr[2,3,1])
print(arr[2,1,3])
print(arr[1,3,4])

10
24
37
43
54
66
58
49

10
24
37
43
54
66
58
49


49

In [15]:
# Section B – Access Complete Rows

# Write a statement to extract:

print(arr[0,1])
print(arr[1,2])
print(arr[2,3])

1.
[15, 16, 17, 18, 19]

2.
[40, 41, 42, 43, 44]

3.
[65, 66, 67, 68, 69]

[15 16 17 18 19]
[40 41 42 43 44]
[65 66 67 68 69]


[65, 66, 67, 68, 69]

In [26]:
# Section C – Access Complete 2D Matrices

# Extract:
first, second, third = arr
print(first)
print(second)
print(third)


[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


In [33]:
# Section D – Column Extraction

print(arr[0,:,0])
print(arr[1,:,2])
print(arr[2,:,4])

#1
#[10, 15, 20, 25]

#2
#[32, 37, 42, 47]


#3
#[54, 59, 64, 69]

[10 15 20 25]
[32 37 42 47]
[54 59 64 69]


In [42]:
# Section E – Slicing
print("#The first two matrices.")
print(arr[:2])
print("#The last two matrices.")
print(arr[-2:])
print("#The first two rows from every matrix.")  
print(arr[:,:2])
print("#The last two rows from every matrix")
print(arr[:,-2:])
print("#The first three columns from every matrix.")
print(arr[:,:,:3])
print("#The last two columns from every matrix.")
print(arr[:,:,-2:])

#Extract:

#The first two matrices.
#The last two matrices.
#The first two rows from every matrix.
#The last two rows from every matrix.
#The first three columns from every matrix.
#The last two columns from every matrix.

#The first two matrices.
[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
#The last two matrices.
[[[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
#The first two rows from every matrix.
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[50 51 52 53 54]
  [55 56 57 58 59]]]
#The last two rows from every matrix
[[[20 21 22 23 24]
  [25 26 27 28 29]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]

 [[60 61 62 63 64]
  [65 66 67 68 69]]]
#The first three columns from every matrix.
[[[10 11 12]
  [15 16 17]
  [20 21 22]
  [25 26 27]]

 [[30 31 32]
  [35 36 37]
  [40 41 42]
  [45 46 47]]

 [[50 51 52]
  [55 56 57]
  [60 61 62]
  [65 66 67]]]
#The last two columns from every matrix.
[[[13 14]
  [18 19]
  [23 24]
  [28 29]]

 [[33 34]
  [38 39]
  [43 44]
  [4

In [ ]:
# Section F – Advanced Slicing

[
 [10, 11, 12],
 [15, 16, 17]
]

In [43]:
print(arr[0,:2,:3])

[[10 11 12]
 [15 16 17]]


In [ ]:
[
 [42, 43, 44],
 [47, 48, 49]
]

In [44]:
print(arr[1,2:,2:])

[[42 43 44]
 [47 48 49]]


In [ ]:
[
 [55, 56],
 [60, 61],
 [65, 66]
]

In [45]:
print(arr[2,1:,:2])

[[55 56]
 [60 61]
 [65 66]]


In [ ]:
[
 [13, 14],
 [18, 19]
]

In [46]:
print(arr[0,:2,-2:])

[[13 14]
 [18 19]]


In [55]:
# Section G –  Questions

Write a single slicing statement to extract:

Every alternate matrix.
Every alternate row from all matrices.
Every alternate column from all matrices.
The first column from every matrix.
The last column from every matrix.
The middle row from every matrix.
The middle column from every matrix.
Reverse the order of matrices.
Reverse the rows inside every matrix.
Reverse the columns inside every matrix.

SyntaxError: invalid syntax (114766384.py, line 3)

In [48]:
#Every alternate matrix.
print(arr[::2,:,:])

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]


In [49]:
#Every alternate row from all matrices.
print(arr[:,::2,:])

[[[10 11 12 13 14]
  [20 21 22 23 24]]

 [[30 31 32 33 34]
  [40 41 42 43 44]]

 [[50 51 52 53 54]
  [60 61 62 63 64]]]


In [50]:
#Every alternate column from all matrices.
print(arr[:,:,::2])

[[[10 12 14]
  [15 17 19]
  [20 22 24]
  [25 27 29]]

 [[30 32 34]
  [35 37 39]
  [40 42 44]
  [45 47 49]]

 [[50 52 54]
  [55 57 59]
  [60 62 64]
  [65 67 69]]]


In [52]:
#The first column from every matrix.
print(arr[:,:,:1])

[[[10]
  [15]
  [20]
  [25]]

 [[30]
  [35]
  [40]
  [45]]

 [[50]
  [55]
  [60]
  [65]]]


In [56]:
#The last column from every matrix.
print(arr[:,:,-1:])

[[[14]
  [19]
  [24]
  [29]]

 [[34]
  [39]
  [44]
  [49]]

 [[54]
  [59]
  [64]
  [69]]]


In [57]:
#The middle row from every matrix.
print(arr[:,1:3,:])

[[[15 16 17 18 19]
  [20 21 22 23 24]]

 [[35 36 37 38 39]
  [40 41 42 43 44]]

 [[55 56 57 58 59]
  [60 61 62 63 64]]]


In [58]:
#The middle column from every matrix.
print(arr[:,:,2:3])

[[[12]
  [17]
  [22]
  [27]]

 [[32]
  [37]
  [42]
  [47]]

 [[52]
  [57]
  [62]
  [67]]]


In [59]:
#Reverse the order of matrices.
print(arr[::-1,:,:])

[[[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [60]:
#Reverse the rows inside every matrix.
print(arr[:,::-1,:])

[[[25 26 27 28 29]
  [20 21 22 23 24]
  [15 16 17 18 19]
  [10 11 12 13 14]]

 [[45 46 47 48 49]
  [40 41 42 43 44]
  [35 36 37 38 39]
  [30 31 32 33 34]]

 [[65 66 67 68 69]
  [60 61 62 63 64]
  [55 56 57 58 59]
  [50 51 52 53 54]]]


In [61]:
#Reverse the columns inside every matrix.
print(arr[:,:,::-1])

[[[14 13 12 11 10]
  [19 18 17 16 15]
  [24 23 22 21 20]
  [29 28 27 26 25]]

 [[34 33 32 31 30]
  [39 38 37 36 35]
  [44 43 42 41 40]
  [49 48 47 46 45]]

 [[54 53 52 51 50]
  [59 58 57 56 55]
  [64 63 62 61 60]
  [69 68 67 66 65]]]


In [47]:
arr = np.array([
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ],

    [
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]
    ],

    [ 
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]
    ]
])

print(arr.shape)

(3, 4, 5)


# 2D ARRAY

In [62]:
import numpy as np

arr = np.array([
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55],
    [60, 61, 62, 63, 64, 65]
])

print(arr.shape)

(6, 6)


In [62]:
import numpy as np

arr = np.array([
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55],
    [60, 61, 62, 63, 64, 65]
])

print(arr.shape)

(6, 6)


In [ ]:
# 2D Array Indexing & Slicing

Extract the following using a single indexing/slicing statement
1. Every alternate row

Expected Output:

[
 [10,11,12,13,14,15],
 [30,31,32,33,34,35],
 [50,51,52,53,54,55]
]

In [65]:
print(arr[::2,:])

[[10 11 12 13 14 15]
 [30 31 32 33 34 35]
 [50 51 52 53 54 55]]


In [ ]:
# 2. Every alternate column

Expected Output:

[
 [10,12,14],
 [20,22,24],
 [30,32,34],
 [40,42,44],
 [50,52,54],
 [60,62,64]
]


In [66]:
print(arr[:,::2])

[[10 12 14]
 [20 22 24]
 [30 32 34]
 [40 42 44]
 [50 52 54]
 [60 62 64]]


In [ ]:
3. First column

Expected Output:

[10,20,30,40,50,60]

In [69]:
print(arr[:,0])

[10 20 30 40 50 60]


In [ ]:
4. Last column

Expected Output:

[15,25,35,45,55,65]

In [71]:
print(arr[:,-1])

[15 25 35 45 55 65]


In [ ]:
5. Middle row

Expected Output:

[40,41,42,43,44,45]

In [72]:
print(arr[3,:])

[40 41 42 43 44 45]


In [ ]:
6. Middle column

Expected Output:

[13,23,33,43,53,63]

In [73]:
print(arr[:,3])

[13 23 33 43 53 63]


In [ ]:
7. First three rows

Expected Output:

[
 [10,11,12,13,14,15],
 [20,21,22,23,24,25],
 [30,31,32,33,34,35]
]


In [74]:
print(arr[:3,:])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]


In [ ]:
8. Last three rows

Expected Output:

[
 [40,41,42,43,44,45],
 [50,51,52,53,54,55],
 [60,61,62,63,64,65]
]


In [87]:
print(arr[-3:,:])

[[40 41 42 43 44 45]
 [50 51 52 53 54 55]
 [60 61 62 63 64 65]]


In [80]:
9. First three columns

Expected Output:

[
 [10,11,12],
 [20,21,22],
 [30,31,32],
 [40,41,42],
 [50,51,52],
 [60,61,62]
]



SyntaxError: invalid syntax (2508920787.py, line 1)

In [88]:
print(arr[:,:3])

[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]
 [50 51 52]
 [60 61 62]]


In [ ]:
10. Last three columns

Expected Output:

[
 [13,14,15],
 [23,24,25],
 [33,34,35],
 [43,44,45],
 [53,54,55],
 [63,64,65]
]

In [89]:
print(arr[:,-3:])

[[13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]]


In [ ]:
11. Reverse all rows

Expected Output:

[
 [60,61,62,63,64,65],
 [50,51,52,53,54,55],
 [40,41,42,43,44,45],
 [30,31,32,33,34,35],
 [20,21,22,23,24,25],
 [10,11,12,13,14,15]
]


In [90]:
print(arr[::-1,:])

[[60 61 62 63 64 65]
 [50 51 52 53 54 55]
 [40 41 42 43 44 45]
 [30 31 32 33 34 35]
 [20 21 22 23 24 25]
 [10 11 12 13 14 15]]


In [ ]:
12. Reverse all columns

Expected Output:

[
 [15,14,13,12,11,10],
 [25,24,23,22,21,20],
 [35,34,33,32,31,30],
 [45,44,43,42,41,40],
 [55,54,53,52,51,50],
 [65,64,63,62,61,60]
]

In [91]:
print(arr[:,::-1])

[[15 14 13 12 11 10]
 [25 24 23 22 21 20]
 [35 34 33 32 31 30]
 [45 44 43 42 41 40]
 [55 54 53 52 51 50]
 [65 64 63 62 61 60]]


In [ ]:
13. Reverse rows and columns simultaneously

Expected Output:


[
 [65,64,63,62,61,60],
 [55,54,53,52,51,50],
 [45,44,43,42,41,40],
 [35,34,33,32,31,30],
 [25,24,23,22,21,20],
 [15,14,13,12,11,10]
]

In [92]:
print(arr[::-1,::-1])

[[65 64 63 62 61 60]
 [55 54 53 52 51 50]
 [45 44 43 42 41 40]
 [35 34 33 32 31 30]
 [25 24 23 22 21 20]
 [15 14 13 12 11 10]]


# Write a single indexing/slicing statement to extract:


In [ ]:

[
 [22,23,24],
 [32,33,34],
 [42,43,44]
]

In [94]:
print(arr[1:4,2:5])

[[22 23 24]
 [32 33 34]
 [42 43 44]]


In [ ]:
[
 [11,13,15],
 [31,33,35],
 [51,53,55]
]


In [95]:
print(arr[::2,1::2])

[[11 13 15]
 [31 33 35]
 [51 53 55]]


In [ ]:
[
 [40,41,42,43,44,45],
 [50,51,52,53,54,55]
]


In [97]:
print(arr[3:5,:])

[[40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [ ]:
import numpy as np

arr = np.array([
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55],
    [60, 61, 62, 63, 64, 65]
])

print(arr.shape)

In [ ]:
[
 [14,15],
 [24,25],
 [34,35],
 [44,45],
 [54,55],
 [64,65]
]

In [98]:
print(arr[:,-2:])

[[14 15]
 [24 25]
 [34 35]
 [44 45]
 [54 55]
 [64 65]]
