# Python Assignment
Topic: 3D Arrays and Dictionaries


# Part A – 3D Arrays  

# Question 1  
## Create the following 3D array.

Layer 1

[1, 2, 3]
[4, 5, 6]

Layer 2

[7, 8, 9]
[10, 11, 12]

In [ ]:
Write a Python program to:

Print the complete 3D array.
Print the first layer.
Print the second row of the second layer.
Print the element 11.

In [1]:
import numpy as np
array_3d = [
    [   
        [1, 2, 3],
        [4, 5, 6]
    ],
    [   
        [7, 8, 9],
        [10, 11, 12]
    ]
]
arr = np.array(array_3d)
#Print the complete 3D array
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
#Print the first layer.
print(arr[0,:,:])

[[1 2 3]
 [4 5 6]]


In [4]:
#Print the second row of the second layer.
print(arr[1,1,:])

[10 11 12]


In [5]:
#Print the element 11.
print(arr[1,1,1])

11


# Question 2  

Using the same 3D array, reverse the order of layers.

Expected Output

Layer 2

[7, 8, 9]
[10,11,12]

Layer 1

[1,2,3]
[4,5,6]

In [6]:
print(arr[-1::-1,:,:])

[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


# Question 3  

##  Reverse every row inside every layer.

Expected Output

In [7]:
print(arr[:,-1::-1,:])

[[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]


# Question 4  

Completely reverse the entire 3D array by reversing:

    the order of layers,
    the order of rows inside each layer,
    the elements inside every row.

Expected Output

[12,11,10]
[9,8,7]
[6,5,4]
[3,2,1]

In [8]:
print(arr[-1::-1,-1::-1,-1::-1])

[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


# Part B – Dictionaries

In [ ]:
# Create a dictionary to store the following student details.

| Key        | Value   |
| ---------- | ------- |
| Roll No    | 101     |
| Name       | Alice   |
| Age        | 20      |
| Department | AI & DS |
| CGPA       | 8.9     |

Display all the information. (use print)

In [9]:
student = {
    "Roll No" : 101,
    "Name" : "Alice",
    "Department" : "AI & DS",
    "CGPA" : 8.9,
    "Age" : 20
}


In [10]:
print(student)

{'Roll No': 101, 'Name': 'Alice', 'Department': 'AI & DS', 'CGPA': 8.9, 'Age': 20}


In [ ]:
# Question 6  

Using the dictionary created above,

    Update the CGPA to 9.2
    Add a new key named City with value Chennai
    Display the updated dictionary.

In [18]:
student['CGPA'] = 9.2
student["City"] = "Chennai"
print(student)

SyntaxError: incomplete input (3166571331.py, line 3)

In [ ]:
# Question 7  

Write a program to print

    all keys
    all values
    all key-value pairs

using appropriate dictionary methods.

In [25]:
#all keys
def dic(d):
    print("Printing all keys")
    for key in d.keys():
        print(key)
    print("Printing all the values")
    for value in d.values():
        print(value)
        
    print("Printing key- value pair")
    for key,value in d.items():
        print( key, " : ", value)


dic(student)

Printing all keys
Roll No
Name
Department
CGPA
Age
City
Printing all the values
101
Alice
AI & DS
9.2
20
Chennai
Printing key- value pair
Roll No  :  101
Name  :  Alice
Department  :  AI & DS
CGPA  :  9.2
Age  :  20
City  :  Chennai


In [ ]:
# Question 8  

Create the following nested dictionary.

students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

Write a program to

    Print the name of Student2.
    Print the age of Student3.
    Display all student names using a loop.

In [26]:
students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

In [28]:
# Print the name of Student2.
print(students['Student2']['Name'])

Alice


In [29]:
#Print the age of Student3.
print(students['Student3']['Age'])

20


In [36]:
#Display all student names using a loop.
for key,value in students.items():
    print(students[key]['Name'])
        

John
Alice
David


In [ ]:
# Question 9  

Create a dictionary of five products.

Example

    Laptop
    Mouse
    Keyboard
    Monitor
    Printer

Each product should contain

    Product Name
    Price
    Quantity

Write a program to

    Display all products.
    Print the product with the highest price.
    Calculate the total inventory value

(Formula:  Inventory Value = Price × Quantity)

In [37]:
products = {
    1: {
        "Product Name": "Laptop",
        "Price": 55000,
        "Quantity": 10
    },
    2: {
        "Product Name": "Mouse",
        "Price": 500,
        "Quantity": 50
    },
    3: {
        "Product Name": "Keyboard",
        "Price": 1200,
        "Quantity": 30
    },
    4: {
        "Product Name": "Monitor",
        "Price": 15000,
        "Quantity": 15
    },
    5: {
        "Product Name": "Printer",
        "Price": 8000,
        "Quantity": 8
    }
}



In [38]:
#Display all products.
print(products)

{1: {'Product Name': 'Laptop', 'Price': 55000, 'Quantity': 10}, 2: {'Product Name': 'Mouse', 'Price': 500, 'Quantity': 50}, 3: {'Product Name': 'Keyboard', 'Price': 1200, 'Quantity': 30}, 4: {'Product Name': 'Monitor', 'Price': 15000, 'Quantity': 15}, 5: {'Product Name': 'Printer', 'Price': 8000, 'Quantity': 8}}


In [39]:
#Print the product with the highest price.
def hig_price(prod):
    High_price = 0
    for i in prod:
        if products[i]['Price'] > High_price:
            High_price = products[i]['Price']
    return High_price
print(hig_price(products))

55000


In [40]:
#Calculate the total inventory value
def total_inv(prod):
    Total = 0
    for i in prod:
        Total = products[i]['Price'] * products[i]['Quantity']
    return Total
print(total_inv(products))

64000


In [ ]:
# Question 10

Create a dictionary of five students and their marks.

Example

    Alice : 85
    Bob : 92
    Charlie : 78
    David : 88
    Emma : 95

Write a Python program to

    Find the student with the highest marks.
    Find the student with the lowest marks.
    Calculate the average marks.
    Display students who scored more than 85.

In [43]:
mark = {
    "Alice" : 85,
    "Bob" : 92,
    "Charlie" : 78,
    "David" : 88,
    "Emma" : 95
}

In [45]:
#Find the student with the highest marks.

def hig_mark(prod):
    High_mark = 0
    for i in prod.values():
        if i > High_mark:
            High_mark = i
    return High_mark
print(hig_mark(mark))

95


In [46]:
#Find the student with the lowest marks.
def low_mark(prod):
    Low_mark = 100
    for i in prod.values():
        if i < Low_mark:
            Low_mark = i
    return Low_mark
print(low_mark(mark))

78


In [49]:
#Calculate the average marks.
def avg_mark(prod):
    mark = 0
    for i in prod.values():
        mark = mark + i
    mark = mark/len(prod)
    return mark
print("Average Mark : ",avg_mark(mark))

Average Mark :  87.6


In [50]:
#Display students who scored more than 85.
for name,mark in mark.items():
    if mark > 85:
        print("Name of Student mark more than 85 :", name)

Name of Student mark more than 85 : Bob
Name of Student mark more than 85 : David
Name of Student mark more than 85 : Emma
